### ISSUE TITLE
python SnapshotFile

### ISSUE THREAD

**Issue by Trickybrain** [diffplug/selfie#297]
To take step in https://github.com/diffplug/selfie-python-wip/issues/7

SnapshotFile
https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/commonMain/kotlin/com/diffplug/selfie/SnapshotFile.kt#L137-L241

SnapshotFile Test
https://github.com/diffplug/selfie-python-wip/blob/2aededc364606e8dcd3c3f69669cb415a0b34b2f/jvm/selfie-lib/src/jvmTest/kotlin/com/diffplug/selfie/SnapshotFileTest.kt#L21-L94

**Comment by nedtwigg** [comment]
@Trickybrain great work! Looks like you've got the whole snapshot file epic completed! A few improvements which will be important to make the rest work:

- `Snapshot.facetData` should be an `ArrayMap[String, SnapshotValue]`
- `SnapshotFile.snapshots` should be an `ArrayMap[String, Snapshot]`

It needs to be `ArrayMap` because `ArrayMap` has a special sort-order for strings, which makes the `/` character the lowest possible character.

**Comment by nedtwigg** [comment]
- Fixed by #334
